<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MailKit" Version="4.11.0" />
    <PackageReference Include="MimeKit" Version="4.11.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="PDFsharp" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Theatre.Core\Theatre.Core.csproj" />
  </ItemGroup>

</Project>
